// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'added': string;
  'banner': string;
  'bannerGrow': string;
  'bookCount': string;
  'bookProgress': string;
  'genres': string;
  'lastBook': string;
  'latestBook': string;
  'metadataProfileId': string;
  'nextBook': string;
  'path': string;
  'qualityProfileId': string;
  'ratings': string;
  'sizeOnDisk': string;
  'sortName': string;
  'status': string;
  'tags': string;
  'useSceneNumbering': string;
}
export const cssExports: CssExports;
export default cssExports;
