// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'authorName': string;
  'bookCount': string;
  'bookType': string;
  'bookTypeLabel': string;
  'container': string;
  'disambiguation': string;
  'expandButton': string;
  'header': string;
  'info': string;
  'left': string;
  'modalFooter': string;
  'name': string;
  'overview': string;
  'poster': string;
  'searchForNewBookContainer': string;
  'searchForNewBookInput': string;
  'searchForNewBookLabel': string;
  'searchForNewBookLabelContainer': string;
  'series': string;
}
export const cssExports: CssExports;
export default cssExports;
