// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dateAdded': string;
  'path': string;
  'quality': string;
  'size': string;
}
export const cssExports: CssExports;
export default cssExports;
