// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'age': string;
  'cell': string;
  'customFormatScore': string;
  'download': string;
  'indexer': string;
  'indexerFlags': string;
  'peers': string;
  'protocol': string;
  'quality': string;
  'rejected': string;
  'size': string;
  'titleContent': string;
}
export const cssExports: CssExports;
export default cssExports;
