// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitlesIconContainer': string;
  'authorNavigationButton': string;
  'authorNavigationButtons': string;
  'authorUpButton': string;
  'backdrop': string;
  'backdropOverlay': string;
  'details': string;
  'detailsLabel': string;
  'header': string;
  'headerContent': string;
  'info': string;
  'links': string;
  'monitorToggleButton': string;
  'overview': string;
  'path': string;
  'poster': string;
  'qualityProfileName': string;
  'sizeOnDisk': string;
  'tags': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'toggleMonitoredContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
