// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'message': string;
  'retagIcon': string;
  'searchForNewBookContainer': string;
  'searchForNewBookInput': string;
  'searchForNewBookLabel': string;
  'searchForNewBookLabelContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
