// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'allBooks': string;
  'book': string;
  'bookType': string;
  'books': string;
  'info': string;
  'missingWanted': string;
}
export const cssExports: CssExports;
export default cssExports;
