// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'books': string;
  'cell': string;
  'monitored': string;
  'selectCell': string;
  'status': string;
  'statusIcon': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
