// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'added': string;
  'authorName': string;
  'bookFileCount': string;
  'genres': string;
  'metadataProfileId': string;
  'path': string;
  'qualityProfileId': string;
  'ratings': string;
  'releaseDate': string;
  'sizeOnDisk': string;
  'status': string;
  'tags': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
