// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitlesIconContainer': string;
  'authorLink': string;
  'backdrop': string;
  'backdropOverlay': string;
  'cover': string;
  'details': string;
  'detailsLabel': string;
  'duration': string;
  'header': string;
  'headerContent': string;
  'info': string;
  'links': string;
  'monitorToggleButton': string;
  'overview': string;
  'qualityProfileName': string;
  'sizeOnDisk': string;
  'tags': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'toggleMonitoredContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
